columnSuffix: ovodddms
contentColumnType: text
fieldGroup: c349cc52-da8a-451d-8a98-751c566168d0 # Common
handle: intro
instructions: ''
name: Intro
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
