defaultPlacement: end
enableVersioning: true
handle: articles
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - 'http://localhost:3000/artikler/{slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0d38519c-a637-4831-8f99-16c480a86356: # craft-lightning
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'artikler/{slug}'
type: channel
