defaultPlacement: end
enableVersioning: true
handle: info
name: Info
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0d38519c-a637-4831-8f99-16c480a86356: # craft-lightning
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'info/{slug}'
structure:
  maxLevels: 2
  uid: d6dfb2a0-ca46-4fe6-9e16-f05e35e25d94
type: structure
