dateModified: 1647288762
email:
  fromEmail: ole@feed.no
  fromName: craft-lightning
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0d38519c-a637-4831-8f99-16c480a86356: craft-lightning # craft-lightning
    7c6d83b3-dbac-412a-90f0-06c7553ac909: Default # Default
    7d795cd5-6c71-4518-a005-10a7beed98c9: Authors # Authors
    7eb7fa21-b426-4227-b3ff-a91ad0bc7317: Demo-gruppe # Demo-gruppe
    24ca6f66-8930-43b3-b4b6-d0fc65a76915: Authors # Authors
    43d369fd-b142-4f7c-8172-597210b3ebd0: 'Public Schema' # Public Schema
    48beea28-0e35-4c22-93c2-04658054ed1c: 'Last updated' # Last updated
    54cca69c-93f8-4647-a5a6-51c8d29a361c: 'Rich text' # Rich text
    0502c870-95b6-46f7-81b4-1f72d3af6519: Article # Article
    3290c17b-421e-4aa8-a8b3-a2421d622482: craft-lightning # craft-lightning
    6832ab3c-eaa1-4647-84c2-be46198d0eac: Text # Text
    8759c6fb-7cf6-42f1-83d5-ca77e42ed045: 'Article Subject' # Article Subject
    089157ce-24a9-4a32-b22b-b124218c6a07: Text # Text
    280555e5-9edc-4032-9376-7c01f724e0bf: SEO # SEO
    a9a45991-6ecb-44f6-aa57-07f0db48ac02: Info # Info
    a5219a7c-bf67-484b-bc8d-efa88dfd8911: 'Main menu' # Main menu
    ad9425cf-a043-40d7-b3d3-decca1e7de73: Default # Default
    c349cc52-da8a-451d-8a98-751c566168d0: Common # Common
    cdfdf5b8-56f7-4edf-bcd7-3532ab9c9b55: Intro # Intro
    cfb673a6-66bc-486c-936d-90b20dc3fe89: Remix # Remix
    d13d6228-1b2f-4c8d-af73-69b118a532b1: Default # Default
    e1223095-3d97-4f75-9aef-66341b5619e4: Articles # Articles
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: H36DNUJAUL5V3VIFYTZFU4ZS
    schemaVersion: 1.0.21
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    licenseKey: VPVMLIR2CUWF2SYE0PCRNX94
    schemaVersion: 3.0.10
  scout:
    edition: standard
    enabled: true
    schemaVersion: 0.1.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: ICUMCGUE6XW1BSX8R0DWLOD8
    schemaVersion: 3.0.11
system:
  edition: pro
  live: true
  name: craft-lightning
  retryDuration: null
  schemaVersion: 3.7.32
  timeZone: Europe/Oslo
